#!/usr/bin/python3
'''
Usage:
    tabular [options] [<input> [<output>]]

Options:
    -o <style>, --output-style <style>          Defines style for columns. [default: uhC]
    -i <string>, --input-separator <string>     Defines characters being used as separators. [default:  \t]
    -s, --sticky-separators                     Multiple separators as one. [default: True]
    -t, --trim-empty                            Deletes empty fields at beginning and end of entries. [default: True]
    -n <string>, --names <string>               Defines names of columns (first character of string stands as separator).
    -1, --first-line-header                     If enabled, makes first string perceived as header.
    -f <string>, --fields <string>              Defines specification of output. [default: l0]
    -L <number>, --lines-inspect <number>       Defines number of strings being counted for calculating field sizes. [default: 0]
    -h, --help                                  Open this message.
    -v, --version                               Version check and finish program execution.
'''

from docopt import docopt
import pprint
import sys
import re

settings = {
    'decostyle': '',
    'headerline': 0,
    'columnline': 0,
    'borderline': 0,
    'fields': ['l0'],
    'lines_inspect': 0,
    'names': [],
    'input_separators': [' '],
    'sticky_separators': True,
    'trim_empty': True,
    'fl_header': False,
    'input': None,
    'output': None
}

# Pretty print function
def pretty_printer(data):
    pp = pprint.PrettyPrinter(stream=sys.stderr)
    pp.pprint(data)

# sys.exit() + streams closing
def sysexit(code):
    if settings['input']:
        settings['input'].close()
    if settings['output']:
        settings['output'].close()

    sys.exit(code)

# Stderr print function
def perr(message, exception=None):
        if exception:
            msg = f'{message}: {exception}'
        else:
            msg = message
        print(msg, file=sys.stderr)

# Argument parsing function
def arg_parse():
    # Getting parameters and options dictionary then print it (for understanding)
    args = docopt(__doc__)
    # pretty_printer(args)
    exit_trigger = False

    # Working with options and parameters using conditions
    if args['--output-style']:
        try:
            list_args = list(args['--output-style'])
            list_args_l = list(args['--output-style'].lower())

            pattern = r'[AUauHBChbc]+'
            matches = re.fullmatch(pattern, args['--output-style'])

            if not matches:
                raise Exception('wrong character')
            if sorted(set(list_args_l)) != sorted(list_args_l):
                raise Exception('duplicated characters')
            if 'a' in set(list_args) and 'u' in set(list_args):
                raise Exception('argument cannot contain "a" and "u" both')
            if 'a' not in set(list_args) and 'u' not in set(list_args):
                raise Exception('argument must contain "a" or "u"')
        except Exception as e:
            perr('Invalid argument in option --output-style', e)
            exit_trigger = True

        if 'a' in list_args:
            settings['decostyle'] = 'ASCII'
        else:
            settings['decostyle'] = 'Unicode'

        if 'h' in list_args:
            settings['headerline'] = 1
        elif 'H' in list_args:
            settings['headerline'] = 2

        if 'c' in list_args:
            settings['columnline'] = 1
        elif 'C' in list_args:
            settings['columnline'] = 2

        if 'b' in list_args:
            settings['borderline'] = 1
        elif 'B' in list_args:
            settings['borderline'] = 2

    if args['--fields']:
        try:
            pattern = r'^([lrjc]\d+)+$'
            matches = re.findall(pattern, args['--fields'])
            for c in args['--fields']:
                if c not in 'lrjc1234567890':
                    raise Exception('wrong character')
            if not matches:
                raise Exception('bad structure')
        except Exception as e:
            perr('Invalid argument in option --fields', e)
            exit_trigger = True

        settings['fields'] = re.findall(r'([a-zA-Z]\d+)', args['--fields'])

    if args['--lines-inspect']:
        try:
            pattern = r'^\d+$'
            matches = re.findall(pattern, args['--lines-inspect'])
            if not matches:
                raise Exception('argument must be a number')
        except Exception as e:
            perr('Invalid argument in option --lines-inspect', e)
            exit_trigger = True

        if not exit_trigger:
            settings['lines_inspect'] = int(args['--lines-inspect'])

    if not args['--sticky-separators']:
        if not args['--input-separator'] == ' \t':
            settings['sticky_separators'] = False

    if args['--input-separator']:
        settings['input_separators'] = list(args['--input-separator'])

    if args['--names']:
        delimiter = args["--names"][0]
        settings['names'] = args['--names'][1:].split(delimiter)

    if not args['--trim-empty']:
        if not args['--input-separator'] == ' \t':
            settings['trim_empty'] = False

    if args['--first-line-header']:
        settings['--first-line-header'] = True

    if args['--version']:
        print('tabular v0.0.1')
        sys.exit()

    if exit_trigger:
        sys.exit(1)

    # Trying to initialize input and output streams
    try:
        if args['<input>']:
            settings['input'] = open(args['<input>'])
        else:
            settings['input'] = sys.stdin
    except Exception as e:
        perr('Cannot open input', e)
        sys.exit(1)

    try:
        if args['<output>']:
            settings['output'] = open(args['<output>'], 'w+')
        else:
            settings['output'] = sys.stdout
    except Exception as e:
        perr('Cannot open output', e)
        sys.exit(1)

    # pretty_printer(settings)

# Reading first n rows where n is -L option value
def read_first_part():
    rows = []

    if settings['lines_inspect'] != 0:
        for _ in range(settings['lines_inspect']):
            row = settings['input'].readline()
            if not row:
                break
            rows.append(row.rstrip('\n\r'))
    else:
        while True:
            row = settings['input'].readline()
            if not row:
                break
            rows.append(row.rstrip('\n\r'))

    return rows

# Function for filtering empty strings in splitted row array
def is_not_empty(string):
    return string != ''

# Making string array from rows divided by --input-separator values
def split_row(row):
    a_row = []
    rpl = settings['input_separators'][0]

    if settings['input_separators'] == [' ', '\t']:
        a_row = row.split()
    else:
        for d in settings['input_separators']:
            if d != rpl:
                row = row.replace(d, rpl)
        if settings['sticky_separators']:
            a_row = list(filter(is_not_empty, row.split(rpl)))
        else:
            a_row = row.split(rpl)

    return a_row

# Calculating maximum lengths of column values
def compute_fields(rows):
    s_rows = []
    if settings['names']:
        s_rows.append(settings['names'])
    for row in rows:
        s_rows.append(split_row(row))
    rows = s_rows

    max_ls = []

    if rows:
        for i in range(max(map(len, rows))):
            max_l = max(len(row[i]) for row in rows if i < len(row))
            max_ls.append(max_l)
    else:
        max_ls = [0]

    return max_ls

# Making string as row for output and then writing it
def write_row(fspec, row):
    if settings['trim_empty']:
        row = row.strip()
    row = split_row(row)
    str_row = ''

    for i in range(len(fspec)):
        if i < len(row):
            str_row += row[i].ljust(fspec[i])
        else:
            str_row += ''.ljust(fspec[i])

        if i != len(fspec)-1:
            str_row += '|'

    str_row += '\n'
    settings['output'].write(str_row)

def write_names(fspec):
    names = settings['names']
    str_names = ''

    for i in range(len(fspec)):
        if i < len(names):
            str_names += names[i].ljust(fspec[i])
        else:
            str_names += ''.ljust(fspec[i])

        if i != len(fspec)-1:
            str_names += '|'
    str_names += '\n'

    settings['output'].write(str_names)

    sline = ''
    for i in range(len(fspec)):
        sline += '-'*fspec[i]
        if i != len(fspec)-1:
            sline += '+'
    sline += '\n'

    settings['output'].write(sline)

def main():
    arg_parse()

    rows = read_first_part()
    fspec = compute_fields(rows)

    write_names(fspec)

    for row in rows:
        write_row(fspec, row)

    if settings['lines_inspect'] != 0:
        while True:
            row = settings['input'].readline()
            if not row:
                break
            write_row(fspec, row)

main()