.lf 1 tabular.1.pre
.TH "tabular" "24" "September 2023" "1.0" "User Manual"
.SH NAME
tabular - converting csv data into tabular view.

.SH SYNOPSIS
tabular [options] [<input> [<output>]]

.SH OPTIONS
.B -o <string>, --output-style <string>
    The argument encodes the column formatting style. The first letter in the line selects the characters used to frame the fields.

    a for ASCII characters
    u for Unicode graphics

    The following letters encode the drawing of different borders in the table.

    h for the border between the header (if defined) and the content
    c for the border between the columns
    b for the external border of the table.

    If Unicode characters are selected, lowercase letters encode a single line thickness, and uppercase letters encode a double line.
    The default style is assumed to be uhC
    Examples of formatting can be found in the Usage section.

.B -i <string>, --input-separator <string>
    The line specifies all the characters that can separate fields. For example, when specifying ;, both comma and semicolon separate fields.
    By default, space is assumed.

.B -s, --sticky-separators
    A flag, when set, treats multiple consecutive separators as a single separator.
    By default, and if the -i option is not specified, the flag is enabled.

.B -t, --trim-empty
    Removes empty fields at the beginning and end of a row.

.B -n <string>, --names <string>
    The string should contain a list of field names. The first character is the delimiter for names in the specified list, followed by the names separated
    by that delimiter. For example, in the sequence '^\[u2116]^Name^Surname^Share, %', the delimiter is "^", and the resulting field names are
    "\[u2116]", "Name", "Surname", and "Share, %" (percentage share).

    By default, the field names are empty.

    If the option is specified, the table should be displayed with specified headers. If the -n or -1 options are not specified, the header is not displayed.

    You can specify either -n or -1, but not both options together.

    If the list of field names is shorter than the list of fields, the list of field names is extended with empty names.

.B -1, --first-line-header
    Flag indicating that field headers are taken from the first row. By default, it is set to false. You can specify either -n or -1, but not both options together.

.B -f <string>, --fields <string>
    The string contains a specification of fields for output. Each field in the input stream is numbered starting from 1. The string lists the order of output fields
    and the rules for their formatting separated by commas. A field is described by an alignment character and a field number. The alignment characters are as follows:

    r for right alignment
    l for left alignment
    c for centering
    j for justification

    For example, the sequence l2r1 indicates that the second field from the input stream is output first, aligned to the left, followed by the first field aligned to the right.
    Field names, if included, are always left aligned. If the field number is specified as 0, it means all fields not explicitly specified in the specification should be included.
    Thus, r2l0r1 should output the second field first, followed by all except the first field, and finally the first field aligned to the right.
    The default specification is l0, that is, all fields are output with left alignment.

.B -L <number>, --lines-inspect <number>
    This specifies how many lines to read before calculating the field sizes. By default, it is set to 0, which means all lines are included.

.B -h, --help
    Shows help message.

.B -v, --version
    Print the program version and terminate execution.

.SH EXAMPLES
.EX
$ cat input.csv
Name,Age,Country
Alice,30,USA
Bob,25,Canada
Charlie,40,UK

$ ./tabular -o ahcb -i ',' -f r1c3l2 -1 input.csv output.tab

$ cat output.tab
+---------+---------+-----+
|    Name | Country | Age |
+---------+---------+-----+
|   Alice |   USA   | 30  |
|     Bob |  Canada | 25  |
| Charlie |    UK   | 40  |
+---------+---------+-----+
.EE

.SH AUTHOR
hjvcx (dania005888@gmail.com)

.SH REPORTING BUGS
https://github.com/hjvcx/tabular/issues

.SH COPYRIGHT
Copyright © 2023 hjvcx

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the “Software”), to deal in the
Software without restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

.SH SEE ALSO
man:column(1)
