#!/bin/bash
set -x

if command -v python3 &> /dev/null; then
    echo "Updating apt-get..."
    sudo apt-get update

    wait

    echo "Installing python3..."
    sudo apt-get install -y python3

    wait

    echo "Installing python3-pip..."
    sudo apt-get install -y python3-pip
fi

cd "../usr/lib/tabular"

if [ -f requirements.txt ]; then
    echo "Installing Python packages from requirements.txt..."
    pip3 install -r requirements.txt
else
    echo "File requirements.txt does not exist in the directory $(pwd)"
    exit 1
fi

exit 0
